# Generated by Django 5.2.3 on 2025-06-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('jabatan', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('tanggal_bergabung', models.DateField()),
            ],
        ),
    ]
