# Generated by Django 5.2.3 on 2025-06-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_gaji',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
